### ISSUE TITLE
[1 request] uml chapter - accessibility ~ 1hr

### ISSUE THREAD

**Issue by llarall** [setextbook/setextbook#10]
feedback:
I am writing to request if you could increase the size of the text used when illustrating the graphical representation of multiplicity in 5.6.1. In particular, it is hard to see the 0..* notation visually. I understand that it is explained in the accompanying text, but it is difficult to see it when visually referring back to the resource.

**Comment by setextbook** [comment]
This should be improved in the second edition. Select the images to easily enlarge.
https://open.oregonstate.education/setextbook/chapter/uml-class/
