### ISSUE TITLE
[1 request] csh chapter - introductory sentences + Abi/Pat/Tim perspectives ~ 6hrs

### ISSUE THREAD

**Issue by llarall** [setextbook/setextbook#12]
feedback:
Heuristics Section was rough, with all the examples. I needed a better opening explanation of what these are, something like:
"These personas are used in a series of 8 Heuristics, aka tests that rate how well they do with a given UX element", and then some more explanation of (possibly) fewer examples. 
So, for instance, Example 1 in 8.3.1 would benefit from rating each of the three descriptions from the perspectives of Abi, Pat, and Tim, with examples both of good and bad descriptions for features.
To elaborate, one of the example extensions might be overly vague in its description of itself, which could motivate Tim ("Oh, stuff to figure out!") but would make Abi and Pat decide it isn't worth the time (doubly so for Abi, who's also highly risk-averse on top of being task-focused).

**Comment by setextbook** [comment]
I liked the idea of persona reactions to each design example. Added in section edition. Chapter has also been rewritten, hopefully is better now.
https://open.oregonstate.education/setextbook/chapter/inclusivity-heuristics/
