### ISSUE TITLE
[5 requests] requirements chapter - more examples ~ 6hrs

### ISSUE THREAD

**Issue by llarall** [setextbook/setextbook#6]
more examples of user stories, given-when format, acceptance criteria, quality attributes, etc.

more examples of how quality attributes are used

**Comment by setextbook** [comment]
In second edition > Chapter 3, “Requirements”: Added examples for INVEST; added more quality attributes and explanations; added a “constraints” type of nonfunctional requirements; enhanced the user story, given-when-then, and Definition of Done examples; linked to more use case examples; added more information about what makes a good requirement; and improved the summary.
https://open.oregonstate.education/setextbook/chapter/requirements/
